# Generated by Django 3.0.5 on 2020-10-19 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreementid', models.CharField(default=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('monthrent', models.PositiveIntegerField()),
                ('hownername', models.CharField(max_length=100)),
                ('contractperiod', models.PositiveIntegerField()),
                ('startdate', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('increment', models.PositiveIntegerField(default=False)),
                ('incrementamount', models.PositiveIntegerField(default=False)),
                ('incrementstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btsid', models.PositiveIntegerField(null=True)),
                ('btsname', models.CharField(max_length=100)),
                ('todate', models.DateField()),
                ('monthrent', models.PositiveIntegerField(default=False)),
                ('totalmonth', models.PositiveIntegerField(blank=True, null=True)),
                ('totalrent', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('hownername', models.CharField(max_length=100)),
                ('contractperiod', models.PositiveIntegerField(default=False)),
                ('checkstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=13)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
