# Generated by Django 3.0.5 on 2020-10-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0002_auto_20201019_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='agreementid',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
