# Generated by Django 3.0.5 on 2020-10-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0004_auto_20201019_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreementid',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='agreementid',
            field=models.CharField(max_length=30),
        ),
    ]
