# Generated by Django 3.0.5 on 2020-10-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0005_auto_20201019_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='incrementamount',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='rent',
            name='monthincrement',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
